USE [master]
GO
/****** Object:  Database [ScavengerHunt]    Script Date: 4/13/2020 6:06:43 PM ******/

ALTER DATABASE [ScavengerHunt] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ScavengerHunt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ScavengerHunt] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ScavengerHunt] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ScavengerHunt] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ScavengerHunt] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ScavengerHunt] SET ARITHABORT OFF 
GO
ALTER DATABASE [ScavengerHunt] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ScavengerHunt] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ScavengerHunt] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ScavengerHunt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ScavengerHunt] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ScavengerHunt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ScavengerHunt] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ScavengerHunt] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ScavengerHunt] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ScavengerHunt] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ScavengerHunt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ScavengerHunt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ScavengerHunt] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ScavengerHunt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ScavengerHunt] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ScavengerHunt] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ScavengerHunt] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ScavengerHunt] SET RECOVERY FULL 
GO
ALTER DATABASE [ScavengerHunt] SET  MULTI_USER 
GO
ALTER DATABASE [ScavengerHunt] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ScavengerHunt] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ScavengerHunt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ScavengerHunt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ScavengerHunt] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'ScavengerHunt', N'ON'
GO
ALTER DATABASE [ScavengerHunt] SET QUERY_STORE = OFF
GO
USE [ScavengerHunt]
GO
/****** Object:  Table [dbo].[Hunt]    Script Date: 4/13/2020 6:06:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hunt](
	[HuntId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[Inactive] [bit] NOT NULL,
 CONSTRAINT [PK_Hunt] PRIMARY KEY CLUSTERED 
(
	[HuntId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HuntStep]    Script Date: 4/13/2020 6:06:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HuntStep](
	[HuntStepId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](200) NOT NULL,
	[Content] [nvarchar](max) NOT NULL,
	[Image] [nvarchar](100) NULL,
	[Url] [nvarchar](50) NULL,
	[HuntId] [int] NOT NULL,
	[PreviousStep] [int] NULL,
 CONSTRAINT [PK_HuntStep] PRIMARY KEY CLUSTERED 
(
	[HuntStepId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HuntStepLink]    Script Date: 4/13/2020 6:06:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HuntStepLink](
	[HuntStepLinkId] [int] IDENTITY(1,1) NOT NULL,
	[CurrentStep] [int] NOT NULL,
	[NextStep] [int] NOT NULL,
	[CorrectResponse] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_HuntStepLink] PRIMARY KEY CLUSTERED 
(
	[HuntStepLinkId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Hunt] ADD  CONSTRAINT [DF_Hunt_Inactive]  DEFAULT ((0)) FOR [Inactive]
GO
ALTER TABLE [dbo].[HuntStep]  WITH CHECK ADD  CONSTRAINT [FK_HuntStep_Hunt] FOREIGN KEY([HuntId])
REFERENCES [dbo].[Hunt] ([HuntId])
GO
ALTER TABLE [dbo].[HuntStep] CHECK CONSTRAINT [FK_HuntStep_Hunt]
GO
ALTER TABLE [dbo].[HuntStep]  WITH CHECK ADD  CONSTRAINT [FK_HuntStep_HuntStepLink] FOREIGN KEY([PreviousStep])
REFERENCES [dbo].[HuntStepLink] ([HuntStepLinkId])
GO
ALTER TABLE [dbo].[HuntStep] CHECK CONSTRAINT [FK_HuntStep_HuntStepLink]
GO
ALTER TABLE [dbo].[HuntStepLink]  WITH CHECK ADD  CONSTRAINT [FK_HuntStepLink_HuntStep] FOREIGN KEY([CurrentStep])
REFERENCES [dbo].[HuntStep] ([HuntStepId])
GO
ALTER TABLE [dbo].[HuntStepLink] CHECK CONSTRAINT [FK_HuntStepLink_HuntStep]
GO
ALTER TABLE [dbo].[HuntStepLink]  WITH CHECK ADD  CONSTRAINT [FK_HuntStepLink_HuntStep1] FOREIGN KEY([NextStep])
REFERENCES [dbo].[HuntStep] ([HuntStepId])
GO
ALTER TABLE [dbo].[HuntStepLink] CHECK CONSTRAINT [FK_HuntStepLink_HuntStep1]
GO
USE [master]
GO
ALTER DATABASE [ScavengerHunt] SET  READ_WRITE 
GO
