# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop, release/* ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macOS-latest]
        configuration: [Release, Debug]
        
    runs-on: ${{ matrix.runs-on }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Setup .NET Core SDK 3.x
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.100'
        
    - name: Build Site in ${{ matrix.configuration }} Mode
      run: dotnet build -c ${{ matrix.configuration }} ScavengerHunt.sln
      working-directory: Source
